# Generated by Django 5.1.4 on 2025-01-04 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_book_delete_user_uploadedfile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='published_year',
            new_name='year_published',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='book_file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
